# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=500)),
                ('sentiment', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=30)),
            ],
        ),
    ]
